In [67]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [68]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [69]:
!pwd

/content


In [70]:
!ls


drive  sample_data


In [71]:
dataset = pd.read_csv('/content/drive/MyDrive/Churn_Modelling.csv')
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [72]:
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [73]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [74]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [75]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x_1 = LabelEncoder()
x[:, 1] = labelencoder_x_1.fit_transform(x[:, 1])
labelencoder_x_2 = LabelEncoder()
x[:, 2] = labelencoder_x_2.fit_transform(x[:, 2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [76]:
# Splitting the dataset into Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [77]:
len(dataset)

10000

In [78]:
len(x_test)

2000

In [79]:
len(x_train)

8000

In [80]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [81]:

#Classical ML

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)
pred = clf.predict(x_test)

In [82]:
# Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)

print(cm)

[[1350  245]
 [ 184  221]]


In [83]:
# Accuracy score
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test, pred)
print(score*100)

78.55


In [84]:
# Accuracy of decision Tree classifier is around 80%

In [85]:
## Random forest
#Classical ML

from sklearn.ensemble import RandomForestClassifier
clf2 = RandomForestClassifier(n_estimators=200) #n_estimators means the number of decision trees
clf2.fit(x_train, y_train)
pred2 = clf2.predict(x_test)

In [86]:
# Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test, pred2)

print(cm2)

[[1520   75]
 [ 199  206]]


In [87]:
# Accuracy score
from sklearn.metrics import accuracy_score

score2 = accuracy_score(y_test, pred2)
print(score2*100)

86.3


In [88]:
# Accuracy score for random forest is 87%

In [89]:
## ANN

In [90]:
# Now let's make the ANN
# Importing the Keras Libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [91]:
# Initialising the ANN
classifier = Sequential()
#units: It's an art, comes by experience, input+
#initializer: how your weights are updated
#relu activation function
#input_dim: input shape (shape of the data, how many features do we have in the data)
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))

#Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the third hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding Output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [92]:
len(x_train)

8000

In [93]:
# Compile the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
y_train[0]
# Fitting the ANN to the Training set
classifier.fit(x_train, y_train, batch_size =10, epochs = 50)

Epoch 1/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7881 - loss: 0.5710
Epoch 2/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7936 - loss: 0.4376
Epoch 3/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7994 - loss: 0.4269
Epoch 4/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8090 - loss: 0.4179
Epoch 5/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8255 - loss: 0.4186
Epoch 6/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8267 - loss: 0.4139
Epoch 7/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8288 - loss: 0.4189
Epoch 8/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8315 - loss: 0.4196
Epoch 9/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8340 - loss: 0.4164
Epoch 10/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8347 - loss: 0.4057
Epoch 11/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8350 - loss: 0.4087
Epoch 12/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [94]:
# Part 3 - Making predictions and evaluating the model
# predicting the Test set results
y_pred_ann = classifier.predict(x_test)
y_pred_ann = (y_pred_ann > 0.5)

cm3 = confusion_matrix(y_test, y_pred_ann)
print(cm3)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[1544   51]
 [ 268  137]]


In [95]:
# Making the confusion Matrix
from sklearn.metrics import accuracy_score

score3 = accuracy_score(y_test,y_pred_ann)
print(score3*100)

84.05


In [97]:
"""#Importing few libraries for k-folds
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
  classifier = Sequential()
  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
  classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
  classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
  return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)

accuracies = cross_val_score(estimator = classifier, x = x_train, y = y_train, cv =10, n_jobs = -1)
mean1 = accuracies.mean()
variance = accuracies.std()
"""

"#Importing few libraries for k-folds\nfrom keras.wrappers.scikit_learn import KerasClassifier\nfrom sklearn.model_selection import cross_val_score\nfrom keras.models import Sequential\nfrom keras.layers import Dense\n\ndef build_classifier():\n  classifier = Sequential()\n  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))\n  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))\n  classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))\n  classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])\n  return classifier\n\nclassifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)\n\naccuracies = cross_val_score(estimator = classifier, x = x_train, y = y_train, cv =10, n_jobs = -1)\nmean1 = accuracies.mean()\nvariance = accuracies.std()\n"

# Convolutional Neural Networks
